name: Build and Deploy to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'tasky/**'

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  ECR_REGISTRY: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: patrick-ecr-private

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/github_oidc_role
        role-session-name: GitHubActions-DockerBuild-Tasky
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create tasky app file
      run: |
        cd tasky
        echo "patrick" >> wizexercise.txt
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        cd tasky/tasky
        docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest